
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: open-telemetry-collector
  namespace: otel
spec:
  image: public.ecr.aws/aws-observability/aws-otel-collector:latest
  mode: daemonset
  #tolerations:
  #  - key: "node-type"
  #    operator: "Equal"
  #    value: "devops-tools"
  #    effect: "NoSchedule"
  config: |
    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318            

    processors:
      batch:

    exporters:
      debug:
        verbosity: detailed
      awsxray:
        region: 'us-east-1'
      awsemf:
        region: 'us-east-1'

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [awsxray]
        metrics:
          receivers: [otlp]
          exporters: [awsemf]  

      extensions: [pprof]
      telemetry:
        logs:
          level: debug
