apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    run: backend
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
      run: backend
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: {{ .Values.backend.historyLimitReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
        run: backend
    spec:
      serviceAccountName: {{ .Values.backend.external_secret.service_account_name }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          env:
            - name: CURRENT_COMMIT
              value: '{{ .Values.backend.image.tag }}'
            - name: OBSERVABILITY_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.backend.external_secret.secret_name }}
                  key: OBSERVABILITY_NODE_USERNAME 
            - name: OBSERVABILITY_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.backend.external_secret.secret_name }}
                  key: OBSERVABILITY_NODE_PASSWORD
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-cm
          - secretRef:
              name: {{ .Values.backend.external_secret.secret_name }}
          readinessProbe:
            httpGet:
              path: /{{ .Values.backend.configmap.CONTEXT }}/health/readiness
              port: {{ .Values.backend.service.data.target_port }}
            failureThreshold: {{ $.Values.health.readiness.failureThreshold }}
            initialDelaySeconds: {{ $.Values.health.readiness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.health.readiness.periodSeconds }}
            successThreshold: {{ $.Values.health.readiness.successThreshold }}
            timeoutSeconds: {{ $.Values.health.readiness.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /{{ .Values.backend.configmap.CONTEXT }}/health/liveness
              port: {{ .Values.backend.service.data.target_port }}
            failureThreshold: {{ $.Values.health.liveness.failureThreshold }}
            initialDelaySeconds: {{ $.Values.health.liveness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.health.liveness.periodSeconds }}
            successThreshold: {{ $.Values.health.liveness.successThreshold }}
            timeoutSeconds: {{ $.Values.health.liveness.timeoutSeconds }}
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
