---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.external_secret.external_secret_role }}"
  name: "{{ .Values.external_secret.service_account_name }}"
  namespace: backend

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ .Values.external_secret.secret_store_name }}"
  namespace: backend
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: "{{ .Values.external_secret.service_account_name }}"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-ext-secret
  namespace: backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: "{{ .Values.external_secret.secret_store_name }}"
    kind: SecretStore
  target:
    name: "{{ .Values.external_secret.secret_name }}" # Secret name in k8s
  dataFrom:
    - extract:
        key: "{{ .Values.external_secret.secret_key }}"
