apiVersion: v1
kind: Namespace
metadata:
  name: backend
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: otel
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: amazon-cloudwatch
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"