apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    run: backend
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
      run: backend
  revisionHistoryLimit: {{ .Values.backend.historyLimitReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
        run: backend
    spec:
      serviceAccountName: {{ .Values.backend.external_secret.service_account_name }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          env:
            - name: CURRENT_COMMIT
              value: '{{ .Values.backend.image.tag }}'
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-cm
          - secretRef:
              name: {{ .Values.backend.external_secret.secret_name }}
          readinessProbe:
            httpGet:
              path: /{{ .Values.backend.configmap.CONTEXT }}/health/readiness
              port: {{ .Values.backend.service.data.target_port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /{{ .Values.backend.configmap.CONTEXT }}/health/liveness
              port: {{ .Values.backend.service.data.target_port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
