apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: infra/monitoring/metric-server
    repoURL: https://gitlab.com/arquitectura-prisma/issuing/api-program-issuing/gitops/k8s-manifests-dev.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
