apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-sc
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.backend.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
